version: '3'

services:
  # Kafka 服务
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_NAME_INTERNAL=INTERNAL
      - KAFKA_LISTENER_INTERNAL_PORT=9093
      - KAFKA_LISTENER_PORT=9093
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_NAME_EXTERNAL=EXTERNAL
      - KAFKA_LISTENER_EXTERNAL_PORT=9092
      - KAFKA_LISTENER_INTERNAL=INTERNAL
    ports:
      - "9092:9092"  # Kafka 外部端口
    depends_on:
      - zookeeper
    networks:
      - flink-kafka-network

  # Zookeeper 服务
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - flink-kafka-network

  # Flink JobManager
  jobmanager:
    image: apache/flink:1.13.6
    command: jobmanager
    ports:
      - "8081:8081"  # Flink Web UI
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - flink-kafka-network

  # Flink TaskManager
  taskmanager:
    image: apache/flink:1.13.6
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    depends_on:
      - jobmanager
    networks:
      - flink-kafka-network

  # Redis 服务
  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Redis 端口
    networks:
      - flink-kafka-network

networks:
  flink-kafka-network:
    driver: bridge
